### PR TITLE
Add ability to configure deployment failure email 

### LINKED ISSUE #42: Feature Request: Set Notification Settings For Site
## Problem
Forge provides a useful set of notification settings for each site, including "Deployment Failure Emails", "Deployment Webhooks", and "Slack Deployment Notifications". 

image

However there is no way to set these for generated deploy-preview sites.

## Solution
It would be nice to have configuration options for each of these settings.

### PR DESCRIPTION
**Pull request by GlitchWitch**
Fixes #42 and adds support for setting a custom deployment failure email

### CODE REVIEW

**Comment by bakerkretzmar** [comment]
Haha you beat me to it, thanks! Just going to test out the API manually to double check some validation and formatting and I'll get this merged.

**Comment by GlitchWitch** [comment]
Awesome! Yeah just wanted to save you some time :)

I haven't had a chance to fully test this on our environment yet (and likely won't today, but sounds like you're on it) hopefully it helps!

**Comment by bakerkretzmar** [comment]
@GlitchWitch can you update this PR to allow maintainer edits so I can push to it?

**Comment by GlitchWitch** [comment]
Looks like I cannot do that due to a limitation in Github ([source](https://github.com/orgs/community/discussions/5634)), will close this out and reopen from my personal repo.

**Pull request closed without merging**
